### ISSUE TITLE
Comment reader macro #_ leaves symbols colored as if they're not commented

### ISSUE THREAD

**Issue by oryband** [sogaiu/tree-sitter-clojure#14] opened 2021-07-12 14:25 UTC
Example: note i'm calling `:TSHighlightCapturesUnderCursor` with the cursor on the `partial` statement, and that some statements in the line are not colored in grey (commented) even though the entire line should be commented out.

![image](https://user-images.githubusercontent.com/115387/125304266-1b424880-e336-11eb-81b5-9eaaa016ffbd.png)

**Comment by sogaiu** [comment] 2021-07-13 03:14
@oryband Thanks for the report.

I'm going to assume that you are using nvim-treesitter with neovim.  Please indicate if otherwise.

I believe I succeeded in replicating the issue or at least something close to it.

I investigated a bit further via a similar setup for emacs and emacs-tree-sitter and didn't manage to reproduce there.

At the moment I'm inclined toward the idea that this may not be a tree-sitter-clojure issue (so perhaps nvim-treesitter or neovim) and I've reported this to the nvim-treesitter folks on zulip: https://nvim-treesitter.zulipchat.com/

If you'd like to see how that discussion turns out, the name of the topic there is "clojure: #_ related highlighting" under the "help" stream.

**Comment by oryband** [comment] 2021-07-13 12:21
@sogaiu thanks. Yes, I am using nvim-treesitter.

**Comment by oryband** [comment] 2021-07-13 16:03
Also, @sogaiu , why not open an issue in github instead of zulip? https://github.com/nvim-treesitter/nvim-treesitter/issues

**Comment by sogaiu** [comment] 2021-07-14 02:53
@oryband Not too long ago I found that folks were pretty responsive on Zulip and I'd like to get a better idea of where the issue might be, so I'm inclined toward asking on Zulip and waiting a bit longer.

However, if you'd like to go ahead and submit an issue at the nvim-treesitter repository or elsewhere, I'm fine with that too :)

**Comment by theHamsta** [comment] 2021-07-14 20:38
The current drawing algorithm is draws smaller ranges over bigger ranges. So as long as the symbols are in the syntax tree and the queries match they will be highlighted.

- A possible solution would be to hide the symbols in the AST by using the `token(...)` function in the grammar.
-  If this is not desired one would have to check with a predicate whether we are in a `#_` region which might be not very efficient if not done in a proper way.
-  At the moment all highlights set by tree-sitter belong to one namespace with a certain priority. It might be possible to change the code in Neovim core to allow for highligh/low priority highlight in order to paint with the `#_` over anything else

**Comment by sogaiu** [comment] 2021-07-18 03:28
@oryband I tried [theHamsta's neovim PR](https://github.com/neovim/neovim/pull/15114) and so far it has been working well.

**Comment by oryband** [comment] 2021-07-18 10:36
Thanks for the quick response guys! Will keep following related threads. Awesome community

**Comment by sogaiu** [comment] 2021-07-26 02:49
@oryband I think this issue has been addressed by a combination of the following:
* https://github.com/neovim/neovim/pull/15114
* https://github.com/nvim-treesitter/nvim-treesitter/pull/1626

How does it look to you?

**Closed** 2021-08-02 02:53 UTC
Labels: issue elsewhere

**Comment by oryband** [comment] 2021-10-13 14:24
> How does it look to you?

Yes. It has been fixed for a while now, sorry for taking so long to reply.
Thanks for everything, and keep up the good work.
